In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/german_temperature_data_1996_2021_from_selected_weather_stations.csv')

In [4]:
df.head()

,MESS_DATUM,164,183,198,222,298,427,591,596,656,...,4501,4625,4642,4745,5142,5397,5440,5546,5629,5705
0,1996-01-01 00:00:00,-10.8,-4.7,-6.6,-2.6,NaN,-9.7,-13.0,-10.5,-5.6,...,-3.0,-13.1,-10.3,-9.6,-10.8,-5.6,-5.0,-10.2,-8.1,-1.7
1,1996-01-01 00:10:00,-10.9,-4.8,-6.6,-2.7,NaN,-9.7,-13.0,-10.7,-5.8,...,-2.5,-13.1,-10.2,-9.6,-10.9,-5.6,-4.9,-10.2,-8.1,-1.8
2,1996-01-01 00:20:00,-11.0,-4.7,-6.6,-2.8,NaN,-9.7,-12.9,-10.7,-5.8,...,-1.9,-13.0,-10.1,-9.6,-10.9,-5.6,-4.8,-10.2,-8.0,-1.9
3,1996-01-01 00:30:00,-11.0,-4.6,-6.6,-2.8,NaN,-9.6,-13.0,-10.7,-5.8,...,-1.5,-12.9,-10.0,-9.7,-11.0,-5.6,-4.6,-10.2,-8.0,-1.9
4,1996-01-01 00:40:00,-10.9,-4.4,-6.6,-2.9,NaN,-9.6,-13.0,-10.7,-5.7,...,-1.1,-12.8,-10.0,-9.8,-11.4,-5.6,-4.6,-10.2,-8.0,-2.0

In [5]:
column_names = ["date"] + [f"station_{col}" for col in df.columns[1:]]
df.columns = column_names

df["date"] = pd.to_datetime(df["date"], errors="coerce")

df.fillna(method="ffill", inplace=True)
df.head()

<ipython-input-5-045b2de4daa7>:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", inplace=True)  # Forward fill method

,date,station_164,station_183,station_198,station_222,station_298,station_427,station_591,station_596,station_656,...,station_4501,station_4625,station_4642,station_4745,station_5142,station_5397,station_5440,station_5546,station_5629,station_5705
0,1996-01-01 00:00:00,-10.8,-4.7,-6.6,-2.6,NaN,-9.7,-13.0,-10.5,-5.6,...,-3.0,-13.1,-10.3,-9.6,-10.8,-5.6,-5.0,-10.2,-8.1,-1.7
1,1996-01-01 00:10:00,-10.9,-4.8,-6.6,-2.7,NaN,-9.7,-13.0,-10.7,-5.8,...,-2.5,-13.1,-10.2,-9.6,-10.9,-5.6,-4.9,-10.2,-8.1,-1.8
2,1996-01-01 00:20:00,-11.0,-4.7,-6.6,-2.8,NaN,-9.7,-12.9,-10.7,-5.8,...,-1.9,-13.0,-10.1,-9.6,-10.9,-5.6,-4.8,-10.2,-8.0,-1.9
3,1996-01-01 00:30:00,-11.0,-4.6,-6.6,-2.8,NaN,-9.6,-13.0,-10.7,-5.8,...,-1.5,-12.9,-10.0,-9.7,-11.0,-5.6,-4.6,-10.2,-8.0,-1.9
4,1996-01-01 00:40:00,-10.9,-4.4,-6.6,-2.9,NaN,-9.6,-13.0,-10.7,-5.7,...,-1.1,-12.8,-10.0,-9.8,-11.4,-5.6,-4.6,-10.2,-8.0,-2.0

In [6]:
df.shape

(1367568, 56)

In [7]:
print("\n📌 Column Names:")
print(df.columns.tolist())

📌 Column Names:
['date', 'station_164', 'station_183', 'station_198', 'station_222', 'station_298', 'station_427', 'station_591', 'station_596', 'station_656', 'station_691', 'station_840', 'station_853', 'station_867', 'station_880', 'station_1001', 'station_1078', 'station_1262', 'station_1358', 'station_1420', 'station_1468', 'station_1544', 'station_1550', 'station_1605', 'station_1684', 'station_1757', 'station_1869', 'station_2014', 'station_2044', 'station_2559', 'station_2638', 'station_2794', 'station_2925', 'station_2985', 'station_3015', 'station_3028', 'station_3126', 'station_3196', 'station_3231', 'station_3366', 'station_3513', 'station_3761', 'station_3811', 'station_3987', 'station_4371', 'station_4466', 'station_4501', 'station_4625', 'station_4642', 'station_4745', 'station_5142', 'station_5397', 'station_5440', 'station_5546', 'station_5629', 'station_5705']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1367568 entries, 0 to 1367567
Data columns (total 56 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   date          1367568 non-null  datetime64[ns]
 1   station_164   1367568 non-null  float64
 2   station_183   1367568 non-null  float64
 3   station_198   1367568 non-null  float64
 4   station_222   1367568 non-null  float64
 5   station_298   1367217 non-null  float64
 6   station_427   1367568 non-null  float64
 7   station_591   1367568 non-null  float64
 8   station_596   1367568 non-null  float64
 9   station_656   1367568 non-null  float64
 10  station_691   1367568 non-null  float64
 11  station_840   1367568 non-null  float64
 12  station_853   1367568 non-null  float64
 13  station_867   1367568 non-null  float64
 14  station_880   1367568 non-null  float64
 15  station_1001  1367568 non-null  float64
 16  station_1078  1367568 non-null  float64
 17  station_1262  1367568 non-null  float64
 18  station_1358  1367568 non-null  float64
 19  station_1420  1367568 non-null  float64
 20  station_1468  1367568 non-null  float64
 21  station_1544  1367568 non-null  float64
 22  station_1550  1367568 non-null  float64
 23  station_1605  1367568 non-null  float64
 24  station_1684  1367568 non-null  float64
 25  station_1757  1367568 non-null  float64
 26  station_1869  1367568 non-null  float64
 27  station_2014  1367568 non-null  float64
 28  station_2044  1367568 non-null  float64
 29  station_2559  1367568 non-null  float64
 30  station_2638  1367568 non-null  float64
 31  station_2794  1367568 non-null  float64
 32  station_2925  1367568 non-null  float64
 33  station_2985  1367568 non-null  float64
 34  station_3015  1367568 non-null  float64
 35  station_3028  1367568 non-null  float64
 36  station_3126  1367568 non-null  float64
 37  station_3196  1367568 non-null  float64
 38  station_3231  1367568 non-null  float64
 39  station_3366  1367568 non-null  float64
 40  station_3513  1367568 non-null  float64
 41  station_3761  1367568 non-null  float64
 42  station_3811  1367568 non-null  float64
 43  station_3987  1367568 non-null  float64
 44  station_4371  1367568 non-null  float64
 45  station_4466  1367568 non-null  float64
 46  station_4501  1367568 non-null  float64
 47  station_4625  1367568 non-null  float64
 48  station_4642  1367568 non-null  float64
 49  station_4745  1367568 non-null  float64
 50  station_5142  1367568 non-null  float64
 51  station_5397  1367568 non-null  float64
 52  station_5440  1367568 non-null  float64
 53  station_5546  1367568 non-null  float64
 54  station_5629  1367568 non-null  float64
 55  station_5705  1367568 non-null  float64
dtypes: datetime64[ns](1), float64(55)
memory usage: 584.3 MB

In [9]:
print(df.isnull().sum())

date              0
station_164       0
station_183       0
station_198       0
station_222       0
station_298     351
station_427       0
station_591       0
station_596       0
station_656       0
station_691       0
station_840       0
station_853       0
station_867       0
station_880       0
station_1001      0
station_1078      0
station_1262      0
station_1358      0
station_1420      0
station_1468      0
station_1544      0
station_1550      0
station_1605      0
station_1684      0
station_1757      0
station_1869      0
station_2014      0
station_2044      0
station_2559      0
station_2638      0
station_2794      0
station_2925      0
station_2985      0
station_3015      0
station_3028      0
station_3126      0
station_3196      0
station_3231      0
station_3366      0
station_3513      0
station_3761      0
station_3811      0
station_3987      0
station_4371      0
station_4466      0
station_4501      0
station_4625      0
station_4642      0
station_4745      0
station_5142      0
station_5397      0
station_5440      0
station_5546      0
station_5629      0
station_5705      0
dtype: int64

In [10]:
df.fillna(method='ffill', inplace=True)

<ipython-input-10-e9443599d05e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [11]:
df["station_298"].fillna(df["station_298"].mean(), inplace=True)

<ipython-input-11-9abbd34573b5>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["station_298"].fillna(df["station_298"].mean(), inplace=True)

In [12]:
df.isnull().sum()

date            0
station_164     0
station_183     0
station_198     0
station_222     0
station_298     0
station_427     0
station_591     0
station_596     0
station_656     0
station_691     0
station_840     0
station_853     0
station_867     0
station_880     0
station_1001    0
station_1078    0
station_1262    0
station_1358    0
station_1420    0
station_1468    0
station_1544    0
station_1550    0
station_1605    0
station_1684    0
station_1757    0
station_1869    0
station_2014    0
station_2044    0
station_2559    0
station_2638    0
station_2794    0
station_2925    0
station_2985    0
station_3015    0
station_3028    0
station_3126    0
station_3196    0
station_3231    0
station_3366    0
station_3513    0
station_3761    0
station_3811    0
station_3987    0
station_4371    0
station_4466    0
station_4501    0
station_4625    0
station_4642    0
station_4745    0
station_5142    0
station_5397    0
station_5440    0
station_5546    0
station_5629    0
station_5705    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.nunique()

date            1367568
station_164         589
station_183         477
station_198         590
station_222         587
station_298         575
station_427         599
station_591         594
station_596         520
station_656         545
station_691         558
station_840         574
station_853         568
station_867         591
station_880         597
station_1001        608
station_1078        602
station_1262        606
station_1358        524
station_1420        573
station_1468        517
station_1544        643
station_1550        581
station_1605        621
station_1684        598
station_1757        590
station_1869        597
station_2014        582
station_2044        592
station_2559        593
station_2638        528
station_2794        613
station_2925        570
station_2985        575
station_3015        577
station_3028        582
station_3126        593
station_3196        588
station_3231        545
station_3366        612
station_3513        530
station_3761        580
station_3811        622
station_3987        575
station_4371        551
station_4466        495
station_4501        524
station_4625        564
station_4642        620
station_4745        595
station_5142        630
station_5397        596
station_5440        588
station_5546        578
station_5629        590
station_5705        585
dtype: int64

In [15]:
df.sample(20)

,date,station_164,station_183,station_198,station_222,station_298,station_427,station_591,station_596,station_656,...,station_4501,station_4625,station_4642,station_4745,station_5142,station_5397,station_5440,station_5546,station_5629,station_5705
63297,1997-03-15 13:30:00,9.6,5.7,10.9,8.3,6.7,11.1,9.4,8.6,5.5,...,3.5,9.3,11.1,9.7,9.9,7.5,9.1,8.0,10.7,9.8
618793,2007-10-07 04:10:00,7.5,11.5,7.4,7.4,5.4,4.4,3.8,5.2,4.1,...,3.1,5.8,3.5,2.4,6.8,4.6,4.7,7.1,6.0,5.8
926338,2013-08-11 21:40:00,13.9,14.5,14.1,9.9,13.4,14.8,12.9,13.7,11.8,...,10.5,15.1,15.7,14.9,12.2,12.2,14.3,13.5,13.5,16.2
441482,2004-05-23 20:20:00,8.7,9.1,6.6,2.6,8.7,8.8,8.2,9.4,4.1,...,0.4,9.6,7.1,7.2,8.0,2.6,6.3,5.7,6.9,8.2
1168642,2018-03-21 13:40:00,5.5,1.8,4.9,1.7,3.2,5.8,4.1,5.0,2.0,...,-2.0,3.4,7.2,3.9,5.9,3.6,1.3,3.5,4.3,5.0
772720,2010-09-10 02:40:00,13.7,12.4,13.5,13.5,12.5,14.3,14.1,13.2,11.2,...,9.8,13.5,14.5,13.8,13.6,10.9,10.7,13.8,14.5,12.3
598147,2007-05-16 19:10:00,14.2,10.3,10.8,11.1,10.6,14.9,10.1,10.7,7.3,...,5.7,10.5,11.1,9.8,14.7,9.6,10.1,10.4,11.8,10.4
411543,2003-10-28 22:30:00,0.2,2.8,0.6,0.9,1.2,0.5,0.9,0.8,0.1,...,-1.1,1.8,-0.8,-1.2,1.3,-1.4,1.6,0.1,0.0,1.9
665727,2008-08-28 02:30:00,17.0,16.7,15.7,13.2,17.1,16.1,16.0,16.2,12.4,...,12.9,15.7,16.2,16.1,16.9,12.3,12.2,15.4,15.9,15.7
1022711,2015-06-12 03:50:00,10.9,11.0,13.4,13.4,7.1,12.9,12.6,13.6,11.5,...,12.4,13.4,13.4,12.5,9.4,14.4,12.3,13.4,11.5,13.0
402408,2003-08-26 12:00:00,22.2,18.8,25.6,23.6,19.4,24.1,20.0,21.1,19.0,...,19.3,19.8,22.0,18.3,19.4,25.4,27.8,23.2,24.6,27.0
115156,1998-03-10 16:40:00,2.7,2.2,4.3,0.8,3.2,4.0,5.8,3.7,-0.6,...,-2.3,5.3,5.3,3.1,2.6,1.5,3.2,3.4,7.9,5.8
1046295,2015-11-22 22:30:00,-1.6,5.2,0.1,-0.3,0.9,-0.2,-1.2,0.8,-2.3,...,-4.7,0.3,-0.3,-0.1,-0.5,-0.3,0.4,-0.4,0.0,0.2
747478,2010-03-18 19:40:00,9.0,7.6,9.8,3.1,9.9,9.4,11.7,9.5,4.5,...,5.9,10.5,10.0,9.3,8.6,9.0,7.9,7.8,7.1,11.3
554366,2006-07-16 18:20:00,21.9,20.9,22.9,19.6,20.9,23.8,23.8,20.6,19.6,...,15.3,23.0,24.4,25.0,20.0,20.7,23.9,23.2,23.7,23.3
1318220,2021-01-23 07:20:00,0.3,0.2,0.9,0.0,-1.4,2.1,-0.2,-0.2,-0.9,...,-2.7,-0.1,-0.7,-0.5,0.1,-0.1,0.7,1.2,1.0,0.9
571906,2006-11-15 13:40:00,13.9,11.7,15.5,15.2,13.0,14.6,13.7,12.8,10.5,...,7.6,12.9,14.2,13.8,13.1,13.8,15.7,13.5,14.9,16.5
189062,1999-08-05 22:20:00,18.0,20.8,18.7,16.2,19.9,16.3,20.8,21.1,15.9,...,13.9,21.3,19.8,17.9,19.9,16.0,19.0,16.8,17.7,20.9
27615,1996-07-10 18:30:00,19.9,14.3,19.9,16.7,15.4,19.9,15.6,15.3,14.1,...,11.6,15.6,18.5,15.5,19.3,16.9,15.5,18.5,20.2,17.6
876188,2012-08-28 15:20:00,20.4,18.8,25.5,25.6,20.3,21.0,20.8,20.0,19.6,...,17.3,21.0,22.2,21.3,19.9,26.4,27.0,23.8,26.1,24.9

In [16]:
df.describe()

,date,station_164,station_183,station_198,station_222,station_298,station_427,station_591,station_596,station_656,...,station_4501,station_4625,station_4642,station_4745,station_5142,station_5397,station_5440,station_5546,station_5629,station_5705
count,1367568,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,...,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06,1.367568e+06
mean,2008-12-31 11:55:00.000002048,9.484858e+00,9.082453e+00,9.835107e+00,8.893043e+00,9.083412e+00,9.953273e+00,9.638912e+00,9.419883e+00,6.983142e+00,...,5.607974e+00,9.562821e+00,9.756826e+00,9.480615e+00,9.352703e+00,8.718081e+00,9.529567e+00,9.224161e+00,1.000883e+01,1.024834e+01
min,1996-01-01 00:00:00,-2.200000e+01,-1.620000e+01,-2.050000e+01,-2.240000e+01,-2.340000e+01,-2.170000e+01,-2.290000e+01,-1.810000e+01,-2.140000e+01,...,-2.090000e+01,-2.070000e+01,-2.370000e+01,-2.280000e+01,-2.870000e+01,-2.330000e+01,-2.150000e+01,-2.100000e+01,-2.130000e+01,-2.000000e+01
25%,2002-07-02 05:57:30,3.300000e+00,3.800000e+00,3.700000e+00,2.700000e+00,3.600000e+00,3.600000e+00,4.000000e+00,4.200000e+00,1.100000e+00,...,-2.000000e-01,3.900000e+00,3.800000e+00,3.900000e+00,3.500000e+00,2.100000e+00,3.100000e+00,3.000000e+00,3.800000e+00,4.000000e+00
50%,2008-12-31 11:55:00,9.400000e+00,8.800000e+00,9.700000e+00,8.700000e+00,8.900000e+00,9.800000e+00,9.500000e+00,9.300000e+00,6.800000e+00,...,5.500000e+00,9.400000e+00,9.500000e+00,9.300000e+00,9.200000e+00,8.400000e+00,9.300000e+00,9.200000e+00,9.800000e+00,1.000000e+01
75%,2015-07-02 17:52:30,1.550000e+01,1.460000e+01,1.570000e+01,1.470000e+01,1.460000e+01,1.610000e+01,1.510000e+01,1.480000e+01,1.250000e+01,...,1.140000e+01,1.510000e+01,1.550000e+01,1.480000e+01,1.530000e+01,1.480000e+01,1.550000e+01,1.520000e+01,1.610000e+01,1.620000e+01
max,2021-12-31 23:50:00,3.730000e+01,4.440000e+01,3.860000e+01,3.670000e+01,3.510000e+01,3.820000e+01,4.560000e+01,3.430000e+01,3.500000e+01,...,3.160000e+01,3.590000e+01,3.860000e+01,3.710000e+01,3.670000e+01,3.690000e+01,3.780000e+01,3.710000e+01,3.770000e+01,3.930000e+01
std,NaN,8.206973e+00,6.636079e+00,8.219281e+00,8.232598e+00,7.335568e+00,8.406305e+00,7.687075e+00,6.918648e+00,7.605967e+00,...,7.762696e+00,7.605558e+00,8.100339e+00,7.654165e+00,7.815985e+00,8.433803e+00,8.426120e+00,8.251740e+00,8.359097e+00,8.235527e+00

In [17]:
!pip install pandas numpy matplotlib seaborn plotly folium geopandas statsmodels

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (0.13.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (5.24.1)
Requirement already satisfied: folium in /usr/local/lib/python3.11/dist-packages (0.19.5)
Requirement already satisfied: geopandas in /usr/local/lib/python3.11/dist-packages (1.0.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.11/dist-packages (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly) (9.0.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.11/dist-packages (from folium) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.11/dist-packages (from folium) (2025.1.0)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.11/dist-packages (from geopandas) (0.10.0)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from geopandas) (3.7.1)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from geopandas) (2.0.7)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.11/dist-packages (from statsmodels) (1.14.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels) (1.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from pyogrio>=0.7.2->geopandas) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (2.3.0)

In [27]:
for col in df.columns[1:]:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df[col].abs()
(df.head())

,date,station_164,station_183,station_198,station_222,station_298,station_427,station_591,station_596,station_656,...,station_4745,station_5142,station_5397,station_5440,station_5546,station_5629,station_5705,z_score,month,year
0,1996-01-01 00:00:00,10.8,4.7,6.6,2.6,9.083412,9.7,13.0,10.5,5.6,...,9.6,10.8,5.6,5.0,10.2,8.1,1.7,2.421567e-16,1,1996
1,1996-01-01 00:10:00,10.9,4.8,6.6,2.7,9.083412,9.7,13.0,10.7,5.8,...,9.6,10.9,5.6,4.9,10.2,8.1,1.8,2.421567e-16,1,1996
2,1996-01-01 00:20:00,11.0,4.7,6.6,2.8,9.083412,9.7,12.9,10.7,5.8,...,9.6,10.9,5.6,4.8,10.2,8.0,1.9,2.421567e-16,1,1996
3,1996-01-01 00:30:00,11.0,4.6,6.6,2.8,9.083412,9.6,13.0,10.7,5.8,...,9.7,11.0,5.6,4.6,10.2,8.0,1.9,2.421567e-16,1,1996
4,1996-01-01 00:40:00,10.9,4.4,6.6,2.9,9.083412,9.6,13.0,10.7,5.7,...,9.8,11.4,5.6,4.6,10.2,8.0,2.0,2.421567e-16,1,1996

In [28]:
df.sample(20)

,date,station_164,station_183,station_198,station_222,station_298,station_427,station_591,station_596,station_656,...,station_4745,station_5142,station_5397,station_5440,station_5546,station_5629,station_5705,z_score,month,year
1109363,2017-02-02 21:50:00,1.4,1.0,1.0,2.4,0.7,0.0,0.2,1.1,1.7,...,2.1,1.2,0.3,1.9,0.7,0.6,2.3,1.333695,2,2017
1141788,2017-09-16 02:00:00,8.3,10.0,7.1,5.0,8.3,8.3,8.2,8.0,6.0,...,7.2,8.4,7.6,7.4,6.9,6.5,6.3,0.106796,9,2017
184691,1999-07-06 13:50:00,19.0,17.7,20.0,19.4,16.9,20.4,19.5,18.0,15.6,...,19.5,17.7,19.7,16.4,18.4,20.8,18.7,1.065574,7,1999
630720,2007-12-29 00:00:00,2.1,4.4,0.1,0.4,4.4,1.2,2.9,3.6,0.1,...,3.0,1.8,3.4,3.3,0.8,0.2,3.9,0.638453,12,2007
534232,2006-02-26 22:40:00,5.5,1.2,5.6,4.6,3.7,6.2,2.7,4.7,9.2,...,1.8,6.3,6.1,4.6,6.0,6.4,3.0,1.742661,2,2006
958874,2014-03-25 20:20:00,2.8,2.7,3.0,1.0,3.2,2.8,4.2,4.5,1.2,...,1.2,2.7,1.3,0.3,3.1,3.4,3.5,0.802039,3,2014
197954,1999-10-06 16:20:00,11.2,12.1,11.7,9.3,11.8,12.0,13.4,12.9,7.1,...,11.7,10.9,8.2,10.1,11.5,11.2,9.9,0.370331,10,1999
962809,2014-04-22 04:10:00,8.2,7.0,8.3,6.9,8.7,9.2,9.0,9.2,5.7,...,7.9,11.5,9.3,6.2,8.7,10.5,7.7,0.052268,4,2014
1173989,2018-04-27 16:50:00,14.5,9.1,14.9,16.6,12.2,15.6,14.6,13.0,11.4,...,14.6,14.2,19.3,19.3,14.9,15.6,19.1,0.424860,4,2018
137328,1998-08-11 16:00:00,24.4,18.3,34.3,33.4,23.2,28.7,29.2,22.0,28.6,...,30.3,22.4,33.2,35.2,33.1,34.2,36.4,1.924403,8,1998
182649,1999-06-22 09:30:00,13.5,13.6,13.4,11.4,14.6,13.3,12.6,13.6,8.1,...,12.3,14.0,12.6,11.0,11.9,13.1,12.2,0.752033,6,1999
798341,2011-03-07 00:50:00,6.0,1.0,3.8,6.3,6.5,5.0,4.4,1.6,5.7,...,3.4,6.6,4.5,1.1,4.1,3.9,2.2,2.124363,3,2011
1243763,2019-08-25 05:50:00,18.9,20.5,18.8,17.9,18.5,20.8,17.4,18.8,19.7,...,17.5,20.0,18.1,16.5,19.1,20.0,18.0,1.283689,8,2019
104960,1997-12-29 21:20:00,3.3,2.9,3.9,2.6,3.0,3.8,2.3,3.0,0.4,...,4.1,2.8,1.3,1.8,2.3,3.7,1.4,0.829303,12,1997
807847,2011-05-12 01:10:00,11.2,10.5,12.1,9.9,6.5,14.4,11.5,10.4,9.4,...,9.6,10.9,12.7,13.9,12.7,14.3,12.9,0.352176,5,2011
1342072,2021-07-07 22:40:00,16.9,17.9,18.3,15.4,15.4,16.6,18.2,18.1,13.5,...,14.9,16.3,14.9,15.3,15.6,17.6,16.5,0.861090,7,2021
1361384,2021-11-19 01:20:00,10.1,10.8,8.3,7.2,11.4,9.7,11.1,11.8,6.1,...,10.4,10.7,4.9,4.8,8.6,9.6,5.5,0.315802,11,2021
853936,2012-03-27 02:40:00,6.2,5.7,3.4,0.4,5.7,3.3,5.3,5.9,5.2,...,5.3,6.1,0.2,0.1,5.2,4.9,5.9,0.461234,3,2012
358468,2002-10-25 08:40:00,5.0,7.2,9.2,9.9,6.0,7.0,7.6,6.2,4.7,...,8.3,6.0,6.6,9.1,6.7,7.0,9.9,0.420337,10,2002
499856,2005-07-03 05:20:00,16.8,17.4,16.3,12.8,16.4,17.6,16.8,17.1,15.8,...,18.3,17.7,13.1,15.8,18.2,17.0,17.3,0.997413,7,2005

In [29]:
pip install pandas plotly gradio

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (5.24.1)
Requirement already satisfied: gradio in /usr/local/lib/python3.11/dist-packages (5.23.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly) (24.2)
Requirement already satisfied: aiofiles<24.0,>=22.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (23.2.1)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.9.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.115.12)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.11/dist-packages (from gradio) (0.5.0)
Requirement already satisfied: gradio-client==1.8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (1.8.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.29.3)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.10.16)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic<2.12,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.11.0)
Requirement already satisfied: pydub in /usr/local/lib/python3.11/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.0.20)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (6.0.2)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.11.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.6)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.46.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.13.2)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.15.2)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.13.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.34.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.8.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.8.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (3.18.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (2.33.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (2.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [33]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import gradio as gr

def load_data():
    print("Loading data...")
    df = pd.read_csv("german_temperature_data_1996_2021_from_selected_weather_stations.csv")
    df.rename(columns={"MESS_DATUM": "date"}, inplace=True)

    df["date"] = pd.to_datetime(df["date"])

    if "month" not in df.columns:
        df["month"] = df["date"].dt.month

    if "year" not in df.columns:
        df["year"] = df["date"].dt.year

    return df
def get_station_columns(df):

    station_columns = [col for col in df.columns if col.startswith('station_')]


    if not station_columns:
        non_station_cols = ['date', 'year', 'month', 'MESS_DATUM']
        station_columns = [col for col in df.columns if col not in non_station_cols
                          and pd.api.types.is_numeric_dtype(df[col])]

    if not station_columns:
        station_columns = [
            "station_Berlin_Tempelhof",
            "station_Hamburg_Fuhlsbuettel",
            "station_Munich_Airport",
            "station_Cologne_Bonn_Airport",
            "station_Frankfurt_Airport",
            "station_Stuttgart_Airport",
            "station_Dresden",
            "station_Hannover",
            "station_Nuremberg",
            "station_Leipzig"
        ]
        print("No station columns detected. Using sample station names.")

    return station_columns

def create_time_series(df, station, start_date, end_date):
    """Create a time series plot for the selected station and date range"""
    if not isinstance(start_date, pd.Timestamp):
        start_date = pd.to_datetime(start_date)
    if not isinstance(end_date, pd.Timestamp):
        end_date = pd.to_datetime(end_date)

    filtered_df = df[(df['date'] >= start_date) & (df['date'] <= end_date)]

    if filtered_df.empty:
        return px.line(title="No data available for the selected date range")

    fig = px.line(filtered_df, x='date', y=station,
                  title=f"Temperature Trend for {station}",
                  labels={"date": "Date", "value": "Temperature (°C)"})

    fig.update_layout(xaxis_title="Date", yaxis_title="Temperature (°C)")
    return fig

def create_heatmap(df, station, start_year, end_year):
    """Create a year-month heatmap for the selected station"""
    filtered_df = df[(df['year'] >= start_year) & (df['year'] <= end_year)]

    if filtered_df.empty:
        return px.imshow(title="No data available for the selected year range")

    pivot_data = filtered_df.pivot_table(index='year', columns='month', values=station, aggfunc='mean')

    fig = px.imshow(pivot_data,
                   labels=dict(x="Month", y="Year", color="Temperature (°C)"),
                   x=[f"Month {i}" for i in range(1, 13)],
                   y=pivot_data.index,
                   title=f"Monthly Temperature Heatmap for {station}",
                   color_continuous_scale="RdBu_r")

    fig.update_layout(coloraxis_colorbar=dict(title="Temp (°C)"))
    return fig

def create_seasonal_box_plot(df, station, start_year, end_year):
    """Create a seasonal box plot for the selected station"""
    filtered_df = df[(df['year'] >= start_year) & (df['year'] <= end_year)]

    if filtered_df.empty:
        return px.box(title="No data available for the selected year range")

    season_map = {
        1: "Winter", 2: "Winter", 3: "Spring",
        4: "Spring", 5: "Spring", 6: "Summer",
        7: "Summer", 8: "Summer", 9: "Fall",
        10: "Fall", 11: "Fall", 12: "Winter"
    }

    filtered_df['season'] = filtered_df['month'].map(season_map)

    fig = px.box(filtered_df, x='season', y=station,
                 title=f"Seasonal Temperature Distribution for {station}",
                 category_orders={"season": ["Winter", "Spring", "Summer", "Fall"]},
                 color='season',
                 color_discrete_map={
                     "Winter": "blue", "Spring": "green",
                     "Summer": "red", "Fall": "orange"
                 })

    fig.update_layout(xaxis_title="Season", yaxis_title="Temperature (°C)")
    return fig

def create_yearly_trend(df, station, start_year, end_year):
    """Create a yearly trend analysis for the selected station"""
    filtered_df = df[(df['year'] >= start_year) & (df['year'] <= end_year)]

    if filtered_df.empty:
        return px.line(title="No data available for the selected year range")

    yearly_avg = filtered_df.groupby('year')[station].mean().reset_index()

    fig = px.scatter(yearly_avg, x='year', y=station,
                     title=f"Yearly Temperature Trend for {station}")

    fig.add_trace(go.Scatter(
        x=yearly_avg['year'],
        y=yearly_avg[station].rolling(window=3).mean(),
        mode='lines',
        name='3-Year Moving Average',
        line=dict(color='red')
    ))

    fig.update_layout(xaxis_title="Year", yaxis_title="Average Temperature (°C)")
    return fig

def create_monthly_comparison(df, stations, year):
    """Create a comparison of multiple stations for a specific year by month"""
    filtered_df = df[df['year'] == year]

    if filtered_df.empty:
        return px.line(title=f"No data available for year {year}")

    monthly_data = filtered_df.groupby('month')[stations].mean().reset_index()

    fig = go.Figure()

    for station in stations:
        fig.add_trace(go.Scatter(
            x=monthly_data['month'],
            y=monthly_data[station],
            mode='lines+markers',
            name=station
        ))

    fig.update_layout(
        title=f"Monthly Temperature Comparison for Year {year}",
        xaxis=dict(
            title="Month",
            tickmode='array',
            tickvals=list(range(1, 13)),
            ticktext=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        ),
        yaxis=dict(title="Temperature (°C)"),
        legend_title="Stations"
    )

    return fig

def detect_anomalies(df, station, threshold=3):
    """Detect temperature anomalies using Z-score method"""
    z_scores = (df[station] - df[station].mean()) / df[station].std()

    anomalies = df[abs(z_scores) > threshold].copy()

    if anomalies.empty:
        return px.scatter(title=f"No anomalies found for threshold {threshold}")

    fig = px.scatter(df, x='date', y=station, opacity=0.5,
                    title=f"Temperature Anomalies for {station} (Z-score > {threshold})")

    fig.add_trace(go.Scatter(
        x=anomalies['date'],
        y=anomalies[station],
        mode='markers',
        marker=dict(color='red', size=10),
        name='Anomalies'
    ))

    fig.update_layout(xaxis_title="Date", yaxis_title="Temperature (°C)")
    return fig

def create_correlation_heatmap(df, stations):
    """Create a correlation heatmap between selected stations"""
    corr_matrix = df[stations].corr()

    fig = px.imshow(corr_matrix,
                   title="Station Temperature Correlation Heatmap",
                   color_continuous_scale="RdBu_r",
                   labels=dict(color="Correlation"))

    fig.update_layout(
        xaxis_title="Stations",
        yaxis_title="Stations"
    )

    return fig

def create_histogram(df, station, bins=30):
    """Create a histogram of temperature distribution for the selected station"""
    fig = px.histogram(df, x=station, nbins=bins,
                      title=f"Temperature Distribution for {station}",
                      labels={station: "Temperature (°C)"},
                      opacity=0.7,
                      color_discrete_sequence=["skyblue"])

    mean_temp = df[station].mean()
    fig.add_vline(x=mean_temp, line_dash="dash", line_color="red",
                 annotation_text=f"Mean: {mean_temp:.2f}°C",
                 annotation_position="top right")

    fig.update_layout(xaxis_title="Temperature (°C)", yaxis_title="Frequency")
    return fig

def display_visualization(viz_type, station, start_date, end_date, year,
                         compare_stations, anomaly_threshold, correlation_stations,
                         histogram_bins):
    """Main function to create and display the selected visualization"""
    try:
        df = load_data()

        if not isinstance(df, pd.DataFrame):
            return "Error: Data not available or invalid format"

        if viz_type == "Time Series":
            return create_time_series(df, station, start_date, end_date)

        elif viz_type == "Monthly Heatmap":
            start_year = pd.to_datetime(start_date).year
            end_year = pd.to_datetime(end_date).year
            return create_heatmap(df, station, start_year, end_year)

        elif viz_type == "Seasonal Box Plot":
            start_year = pd.to_datetime(start_date).year
            end_year = pd.to_datetime(end_date).year
            return create_seasonal_box_plot(df, station, start_year, end_year)

        elif viz_type == "Yearly Trend":
            start_year = pd.to_datetime(start_date).year
            end_year = pd.to_datetime(end_date).year
            return create_yearly_trend(df, station, start_year, end_year)

        elif viz_type == "Station Comparison":
            stations_list = [s.strip() for s in compare_stations.split(",")]
            return create_monthly_comparison(df, stations_list, year)

        elif viz_type == "Anomaly Detection":
            return detect_anomalies(df, station, anomaly_threshold)

        elif viz_type == "Correlation Heatmap":
            stations_list = [s.strip() for s in correlation_stations.split(",")]
            return create_correlation_heatmap(df, stations_list)

        elif viz_type == "Histogram":
            return create_histogram(df, station, histogram_bins)

        else:
            return "Please select a visualization type"

    except Exception as e:
        return f"Error: {str(e)}"

def create_interface():
    try:
        df = load_data()
        station_columns = get_station_columns(df)

        viz_types = [
            "Time Series", "Monthly Heatmap", "Seasonal Box Plot", "Yearly Trend",
            "Station Comparison", "Anomaly Detection", "Correlation Heatmap", "Histogram"
        ]

        with gr.Blocks(title="German Temperature Data Explorer") as app:
            gr.Markdown("# 🌡️ German Temperature Data Explorer")
            gr.Markdown("Explore temperature data from German weather stations (1996-2021)")

            with gr.Row():
                with gr.Column(scale=1):
                    viz_type = gr.Dropdown(viz_types, label="Visualization Type", value="Time Series")

                    station = gr.Dropdown(station_columns, label="Select Station",
                                         value=station_columns[0] if station_columns else None)

                    start_date = gr.Textbox(label="Start Date (YYYY-MM-DD)", value="1996-01-01")
                    end_date = gr.Textbox(label="End Date (YYYY-MM-DD)", value="2021-12-31")

                    with gr.Accordion("Additional Options", open=False):
                        year = gr.Number(label="Year (for Station Comparison)", value=2020, minimum=1996, maximum=2021, step=1)

                        default_compare = ", ".join([station_columns[i] for i in range(min(3, len(station_columns)))])
                        compare_stations = gr.Textbox(label="Stations to Compare (comma-separated)",
                                                    value=default_compare)

                        anomaly_threshold = gr.Slider(label="Anomaly Z-score Threshold", minimum=1.0, maximum=5.0, value=3.0, step=0.1)

                        default_correlation = ", ".join([station_columns[i] for i in range(min(5, len(station_columns)))])
                        correlation_stations = gr.Textbox(label="Stations for Correlation (comma-separated)",
                                                        value=default_correlation)

                        histogram_bins = gr.Slider(label="Histogram Bins", minimum=10, maximum=100, value=30, step=5)

                    generate_btn = gr.Button("Generate Visualization")

                with gr.Column(scale=2):
                    output = gr.Plot(label="Visualization Output")

            with gr.Accordion("Help & Information", open=False):
                gr.Markdown("""
                ## How to Use This Dashboard

                1. **Select a Visualization Type** from the dropdown menu
                2. **Choose a Weather Station** to analyze
                3. **Set the Date Range** for your analysis
                4. Use **Additional Options** for specific visualization settings
                5. Click **Generate Visualization** to create the plot

                ## Visualization Types

                - **Time Series**: Shows temperature changes over time
                - **Monthly Heatmap**: Displays temperatures by month and year
                - **Seasonal Box Plot**: Shows temperature distribution by season
                - **Yearly Trend**: Analyzes yearly temperature trends with moving average
                - **Station Comparison**: Compares multiple stations by month for a specific year
                - **Anomaly Detection**: Identifies unusual temperature readings
                - **Correlation Heatmap**: Shows correlation between station temperatures
                - **Histogram**: Displays the distribution of temperature values
                """)

            with gr.Accordion("Available Stations", open=False):
                station_list_markdown = ", ".join(station_columns)
                gr.Markdown(f"### Available Stations\n{station_list_markdown}")

            generate_btn.click(
                fn=display_visualization,
                inputs=[viz_type, station, start_date, end_date, year,
                       compare_stations, anomaly_threshold, correlation_stations,
                       histogram_bins],
                outputs=output
            )

            viz_type.change(
                fn=lambda x: gr.update(visible=(x == "Station Comparison")),
                inputs=[viz_type],
                outputs=[year]
            )

        return app

    except Exception as e:
        print(f"Error creating interface: {str(e)}")
        with gr.Blocks(title="German Temperature Data Explorer") as app:
            gr.Markdown("# 🌡️ German Temperature Data Explorer")
            gr.Markdown(f"**Error loading data: {str(e)}**")
            gr.Markdown("Please check your data file and ensure it contains the required columns.")
        return app


if __name__ == "__main__":
    create_interface().launch()

Loading data...
Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://0ef512c6308f075d9a.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)